name: Install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
		matrix:
			python-version: [3.8, 3.9, 3.10.x, 3.11]
			os: [ubuntu-latest]
		runs-in: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
